
#Clones the repository

steps:
- name: 'gcr.io/cloud-builders/git'
  id: 'Clone'
  args: ['clone', 'https://github.com/ehienabs/databotsgcp.git']

#Builds the image from the dockerfile

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/databotsami/$SHORT_SHA'
  - './app'

# Pushes the image to container registry

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/databotsami/$SHORT_SHA'
  
# sets the image in the deployment

- name: 'gcr.io/$PROJECT_ID/kustomize'
  args: ['edit', 'set', image 'image=gcr.io/$PROJECT_ID/databotsami/$SHORT_SHA']
  dir: '.'
  env: 
    - "CLOUDSDK_COMPUTE_REGION=us-central1"
    - "CLOUDSDK_CONTAINER_CLUSTER=$PROJECT_ID-gke"

# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./deployment.yaml
  - --location=us-central1
  - --cluster=$PROJECT_ID-gke
